### ISSUE TITLE
有办法将二维码和文本打印在一行上吗？

### ISSUE THREAD

**Issue by jackzhum** [xiaonibaba/uniapp-Bluetooth-print#4]
如题。
网上找了好多，都是直接打印二维码，没有将二维码和文本打在同一行上的方案。

比如：一个标签纸，左边半边放二维码，右半边打文本

**Comment by daleizi** [comment]
好，是否交流下。我的QQ491346467 我现在下载了demo，连接上打印机 ，但是没有用

**Comment by jackzhum** [comment]
@daleizi 我已经放弃这个组件了，这个组件没有办法将文字和二维码打在同一行，我换了成了ZPL方式连接，这个需要打印机支持

**Comment by daleizi** [comment]
我用的是 佳博GP-2120TU的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jack"<notifications@github.com&gt;; 
发送时间: 2021年1月20日(星期三) 下午3:13
收件人: "xiaonibaba/uniapp-Bluetooth-print"<uniapp-Bluetooth-print@noreply.github.com&gt;; 
抄送: "爱音乐"<3106875831@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [xiaonibaba/uniapp-Bluetooth-print] 有办法将二维码和文本打印在一行上吗？ (#4)





 
@daleizi 我已经放弃这个组件了，这个组件没有办法将文字和二维码打在同一行，我换了成了ZPL方式连接，这个需要打印机支持

**Comment by jackzhum** [comment]
> 我用的是 佳博GP-2120TU的
> […](#)

**Comment by jackzhum** [comment]
> 我用的是 佳博GP-2120TU的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jack"<notifications@github.com&gt;; 发送时间: 2021年1月20日(星期三) 下午3:13 收件人: "xiaonibaba/uniapp-Bluetooth-print"<uniapp-Bluetooth-print@noreply.github.com&gt;; 抄送: "爱音乐"<3106875831@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [xiaonibaba/uniapp-Bluetooth-print] 有办法将二维码和文本打印在一行上吗？ (#4) @daleizi 我已经放弃这个组件了，这个组件没有办法将文字和二维码打在同一行，我换了成了ZPL方式连接，这个需要打印机支持 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

这个要看你打印机支不支持了，你可以看看打印机的说明书
